### ISSUE TITLE
Crashes Electron

### ISSUE THREAD

**Issue by JoaoBGusmao** [endel/node-delta#1]
I'm using node-delta on an electron app I am build, but it seem to crash every time I invoke the 'apply' method. Doesn't matter the file size, it simply crashes the app.
I have tested on a clean node app, and works fine. I'm Having crashes issues only with electron.

Sometimes it do what it have to do, finish everything (I mean, the final file is generated just fine), but after 5 seconds the app goes down. If it doesn't happen, it will surely crash if you open the console.
I don't know if it can make difference, but I had to rebuild node-delta using "electron-rebuild" to make it work.
So, any suggestion with what may cause this issue?

**Comment by endel** [comment]
This library is native and needs to be compiled. You can use its plain javascript alternative, here: https://www.npmjs.com/package/fossil-delta

Cheers!
